CREATE TABLE agoda_data (
    proposal_detail_id INT PRIMARY KEY AUTO_INCREMENT,
    proposal_id VARCHAR(255) NOT NULL,
    day_count INT NOT NULL,
    agoda_hotel_location_id VARCHAR(255),
    agoda_location_name VARCHAR(255),
    start_dt DATETIME NOT NULL,
    end_dt DATETIME NOT NULL,
    number_of_rooms INT NOT NULL,
    number_of_adults INT NOT NULL,
    number_of_children INT NOT NULL,
    child_ages_pipe_delimited VARCHAR(50),
    agoda_hotel_id INT,
    agoda_hotel_name VARCHAR(255),
    agoda_hotel_stars FLOAT,
    agoda_hotel_rating FLOAT,
    agoda_hotel_ratings_count INT,
    agoda_hotel_pics_pipe_delimited TEXT,
    agoda_room_pics_pipe_delimited TEXT,
    sleeps_count INT NOT NULL,
    room_price_per_night DECIMAL(10,2),
    risk_free_booking_binary TINYINT,
    cancelation_deadline_dt DATETIME NULL,
    includes_breakfast_binary TINYINT,
    includes_lunch_binary TINYINT,
    includes_dinner_binary TINYINT,
    bed_type VARCHAR(255),
    size_sqm VARCHAR(255),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME,
    active_flg INT DEFAULT 1,
    INDEX idx_deleted_at (deleted_at)
);